#!/bin/bash

set -e

DATASET="$1"

if [ -z "$DATASET" ]; then
    echo "NO DATASET"
    exit
fi

OUTDIR="experiments/vqvae-2/${DATASET}"
MODEL="vqvae2[]"

mkdir -p "$OUTDIR"
echo $MODEL > "$OUTDIR/model"

date >> "$OUTDIR/progress.txt"
./.colorize ./train.py                      \
    --log-to "runs/$OUTDIR"                 \
    --batch-size 260                        \
    --learning-rate "0.0002"                \
    --epochs 150                            \
    images[files=youtube/$DATASET/*]        \
    "$MODEL"                                \
    "$OUTDIR/checkpoint_{epoch:0>5}.pth" | tee -a "$OUTDIR/progress.txt"

# ./render_vae "$DATASET" "$MODEL" "$OUTDIR"
